general.import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 7, y = 7 }
dynamic_padding = true
opacity = 1.0
decorations = "Buttonless"
option_as_alt = "Both"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
