import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 1.0
decorations = "None"
option_as_alt = "Both"

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

